server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: custom-server


from: qwe
